// <auto-generated />
using Kasumi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kasumi.Migrations.Roles
{
    [DbContext(typeof(RolesContext))]
    [Migration("20190619171814_roles")]
    partial class roles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Kasumi.Database.AssignableRole", b =>
                {
                    b.Property<string>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("ServerId");

                    b.HasKey("RoleId");

                    b.ToTable("AssignableRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
